AWSTemplateFormatVersion: "2010-09-09"
Description: "Add Transit Gateway and TG Basic Config"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "VPC Parameters"
        Parameters:
         - DefaultRouteBlock
         - AllPrivateBlock
         - DMZVPCCIDRBlock
         - VPC01CIDRBlock
         - VPC02CIDRBlock

Parameters:

  DefaultRouteBlock:
    Type: String
    Default: 0.0.0.0/0
    Description: "Enter desired CIDR to Default route"

  AllPrivateBlock:
    Type: String
    Default: 10.0.0.0/8
    Description: "Enter desired CIDR to Default route"

  DMZVPCCIDRBlock:
    Type: String
    Default: 10.11.0.0/16
    Description: "Enter desired CIDR to DMZVPC route"

  VPC01CIDRBlock:
    Type: String
    Default: 10.1.0.0/16
    Description: "Enter desired CIDR to VPC1 route"

  VPC02CIDRBlock:
    Type: String
    Default: 10.2.0.0/16
    Description: "Enter desired CIDR to VPC2 route"


Resources:
#########################
# Create-TransitGateWay #
#########################
  TransitGateway01:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      AmazonSideAsn: 65001
      Description: "TGW Route Integration Test"
      AutoAcceptSharedAttachments: "enable"
      DefaultRouteTableAssociation: "disable"
      DefaultRouteTablePropagation: "disable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'

####################################
# Create-TransitGateWay-RouteTable #
####################################

  TransitGatewayRouteTableDMZVPC:
    Type: "AWS::EC2::TransitGatewayRouteTable"
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-DMZVPC-RT'
      TransitGatewayId: !Ref TransitGateway01

##############################################
# Connect to the Transit Gateway#
##############################################

  TransitGatewayAttachmentDMZVPC:
    Type: "AWS::EC2::TransitGatewayAttachment"
    Properties:
      SubnetIds:
        - Fn::ImportValue: !Sub "DMZVPC-TGW-Subnet-A"
        - Fn::ImportValue: !Sub "DMZVPC-TGW-Subnet-B"
      Options:
        ApplianceModeSupport: enable
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Attach-DMZVPC'
      TransitGatewayId: !Ref TransitGateway01
      VpcId:
        Fn::ImportValue: !Sub "DMZVPC"

  TransitGatewayAttachmentVPC01:
    Type: "AWS::EC2::TransitGatewayAttachment"
    Properties:
      SubnetIds:
        - Fn::ImportValue: !Sub "VPC01-TGW-Subnet-A"
        - Fn::ImportValue: !Sub "VPC01-TGW-Subnet-B"
      Options:
        ApplianceModeSupport: enable
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Attach-VPC01'
      TransitGatewayId: !Ref TransitGateway01
      VpcId:
        Fn::ImportValue: !Sub "VPC01"

  TransitGatewayAttachmentVPC02:
    Type: "AWS::EC2::TransitGatewayAttachment"
    Properties:
      SubnetIds:
        - Fn::ImportValue: !Sub "VPC02-TGW-Subnet-A"
        - Fn::ImportValue: !Sub "VPC02-TGW-Subnet-B"
      Options:
        ApplianceModeSupport: enable
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Attach-VPC02'
      TransitGatewayId: !Ref TransitGateway01
      VpcId:
        Fn::ImportValue: !Sub "VPC02"

  TransitGatewayRouteTableAssociationDMZVPC:
    Type: "AWS::EC2::TransitGatewayRouteTableAssociation"
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachmentDMZVPC
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableDMZVPC

  TransitGatewayRouteTableAssociationVPC01:
    Type: "AWS::EC2::TransitGatewayRouteTableAssociation"
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachmentVPC01
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableDMZVPC

  TransitGatewayRouteTableAssociationVPC02:
    Type: "AWS::EC2::TransitGatewayRouteTableAssociation"
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachmentVPC02
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableDMZVPC

  TransitGatewayRoute01DMZVPC:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachmentDMZVPC
      DestinationCidrBlock: !Ref DMZVPCCIDRBlock
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableDMZVPC

  TransitGatewayRoute02DMZVPC:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachmentDMZVPC
      DestinationCidrBlock: !Ref DefaultRouteBlock
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableDMZVPC

  TransitGatewayRoute03DMZVPC:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachmentVPC01
      DestinationCidrBlock: !Ref VPC01CIDRBlock
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableDMZVPC

  TransitGatewayRoute04DMZVPC:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachmentVPC02
      DestinationCidrBlock: !Ref VPC02CIDRBlock
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableDMZVPC

### DMZVPC route table configuration

  DMZVPCAddRoute1:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentDMZVPC    
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref AllPrivateBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId: 
        Fn::ImportValue: !Sub "DMZVPC-PrivateSubnetARouteTableID"

  DMZVPCAddRoute2:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentDMZVPC    
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref AllPrivateBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId: 
        Fn::ImportValue: !Sub "DMZVPC-PrivateSubnetBRouteTableID"

  DMZVPCAddRoute3:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentDMZVPC    
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref VPC01CIDRBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId: 
        Fn::ImportValue: !Sub "DMZVPC-FWOUTSubnetARouteTableID"

  DMZVPCAddRoute4:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentDMZVPC    
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref VPC02CIDRBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId: 
        Fn::ImportValue: !Sub "DMZVPC-FWOUTSubnetARouteTableID"

  DMZVPCAddRoute5:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentDMZVPC    
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref VPC01CIDRBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId: 
        Fn::ImportValue: !Sub "DMZVPC-FWOUTSubnetBRouteTableID"

  DMZVPCAddRoute6:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentDMZVPC    
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref VPC02CIDRBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId: 
        Fn::ImportValue: !Sub "DMZVPC-FWOUTSubnetBRouteTableID"

### VPC01 route table configuration
  VPC01AddRoute1:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentVPC01
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref DefaultRouteBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId:  
        Fn::ImportValue: !Sub "VPC01-PrivateSubnetARouteTableID"

  VPC01AddRoute2:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentVPC01
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref DefaultRouteBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId:  
        Fn::ImportValue: !Sub "VPC01-PrivateSubnetBRouteTableID"

### VPC02 route table configuration
  VPC02AddRoute1:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentVPC02
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref DefaultRouteBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId:  
        Fn::ImportValue: !Sub "VPC02-PrivateSubnetARouteTableID"

  VPC02AddRoute2:
    DependsOn:
      - TransitGateway01
      - TransitGatewayAttachmentVPC02
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref DefaultRouteBlock
      TransitGatewayId: !Ref TransitGateway01
      RouteTableId:  
        Fn::ImportValue: !Sub "VPC02-PrivateSubnetBRouteTableID"
